<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import FullCalendar from '@fullcalendar/vue3'
import dayGridPlugin from '@fullcalendar/daygrid'
import interactionPlugin from '@fullcalendar/interaction'
import { api, type FutureTask, type Plan } from '../api/client'
const today=new Date();const iso=(v:Date)=>v.toISOString().slice(0,10);const plus=(days:number)=>{const v=new Date(today);v.setDate(v.getDate()+days);return iso(v)}
const plans=ref<Plan[]>([]);const tasks=ref<FutureTask[]>([]);const scale=ref(7);const loading=ref(false);const error=ref('');const name=ref('');const startDate=ref(iso(today));const endDate=ref(plus(30));const intro=ref('');const selectedPlan=ref<Plan|null>(null);const progress=ref(0)
const events=computed(()=>tasks.value.map(x=>({id:x.id,title:x.title,date:x.date,classNames:x.done?['task-done']:[`priority-${x.priority}`]})))
const calendarOptions=computed(()=>({plugins:[dayGridPlugin,interactionPlugin],initialView:'dayGridMonth',initialDate:today,editable:false,height:'auto',events:events.value,headerToolbar:{left:'prev,next today',center:'title',right:''},dateClick:(info:{dateStr:string})=>{startDate.value=info.dateStr;endDate.value=info.dateStr}}))
async function load(){loading.value=true;try{plans.value=(await api.plans()).items;const days=Math.min(scale.value,366);tasks.value=(await api.calendar(iso(today),plus(days))).items}catch(e){error.value=e instanceof Error?e.message:'未来数据读取失败'}finally{loading.value=false}}
async function create(){try{await api.createPlan({name:name.value,startDate:startDate.value,endDate:endDate.value,intro:intro.value});name.value='';intro.value='';await load()}catch(e){error.value=e instanceof Error?e.message:'规划创建失败'}}
async function saveProgress(){if(!selectedPlan.value)return;try{await api.setPlanProgress(selectedPlan.value.id,iso(today),progress.value);await load()}catch(e){error.value=e instanceof Error?e.message:'进度保存失败'}}
function choose(plan:Plan){selectedPlan.value=plan;progress.value=plan.progress}
onMounted(load)
</script>
<template><main class="future-page"><header class="future-header"><div><p class="eyebrow">FUTURE / PLANNING SYSTEM</p><h1>未来</h1></div><label>日历跨度 <select v-model.number="scale" @change="load"><option :value="7">7 天</option><option :value="14">14 天</option><option :value="30">30 天</option><option :value="182">半年</option><option :value="365">1 年</option><option :value="1825">5 年</option><option :value="3650">10 年</option><option :value="10950">30 年</option><option :value="36500">100 年</option></select></label></header><p v-if="error" class="error">{{error}}</p><div class="future-grid"><section class="panel plans-panel"><header><h2>进行中的规划</h2><small>{{plans.length}} 项</small></header><button v-for="plan in plans" :key="plan.id" class="plan-item" :class="{selected:selectedPlan?.id===plan.id}" @click="choose(plan)"><b>{{plan.name}}</b><small>{{plan.startDate}} → {{plan.endDate}}</small><div class="progress-line"><i :style="{width:`${plan.progress}%`}"/></div><small>计划 {{plan.progress.toFixed(0)}}% · 时间 {{plan.timeProgress.toFixed(0)}}%</small></button><form class="plan-form" @submit.prevent="create"><h3>新建规划</h3><input v-model.trim="name" placeholder="名称" required/><div class="date-row"><input v-model="startDate" type="date" required/><input v-model="endDate" type="date" required/></div><textarea v-model="intro" placeholder="简介（Markdown）"/><button class="primary">创建规划</button></form></section><section class="panel plan-detail"><template v-if="selectedPlan"><header><div><h2>{{selectedPlan.name}}</h2><small>{{selectedPlan.startDate}} → {{selectedPlan.endDate}}</small></div><span>{{selectedPlan.progress.toFixed(0)}}%</span></header><p>{{selectedPlan.intro||'暂无简介'}}</p><form @submit.prevent="saveProgress" class="progress-form"><label>今日计划进度 {{progress}}%<input v-model.number="progress" type="range" min="0" max="100"/></label><button class="primary">保存进度</button></form></template><div v-else class="empty">选择一项规划查看进度。</div></section></div><section class="panel future-calendar"><header><h2>待办日历</h2><small v-if="loading">读取中…</small></header><FullCalendar :options="calendarOptions"/></section></main></template>