<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import FullCalendar from '@fullcalendar/vue3'
import dayGridPlugin from '@fullcalendar/daygrid'
import interactionPlugin from '@fullcalendar/interaction'
import { MdEditor } from 'md-editor-v3'
import 'md-editor-v3/lib/style.css'
import MetricLine from '../components/MetricLine.vue'
import { api, type MoodTag, type NowData, type Plan } from '../api/client'
const data=ref<NowData>({diary:{id:'',entryDate:'',content:'',secret:false,commentable:false},moods:[],bodies:[],tasks:[]});const tags=ref<MoodTag[]>([]);const plans=ref<Plan[]>([]);const selectedTags=ref<string[]>([]);const moodNote=ref('');const bodyNote=ref('');const bodyScore=ref(70);const savedAt=ref('');const now=ref(new Date());const leftWidth=ref(Number(localStorage.getItem('now-left-width')||45));const dragging=ref(false);const error=ref('');let timer:number|undefined;let clock:number|undefined
const lunar=computed(()=>new Intl.DateTimeFormat('zh-CN-u-ca-chinese',{month:'long',day:'numeric'}).format(now.value));const dateLabel=computed(()=>new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',weekday:'long'}).format(now.value));const timeLabel=computed(()=>now.value.toLocaleTimeString('zh-CN',{hour12:false}));const moodValues=computed(()=>data.value.moods.map(x=>x.value));const bodyValues=computed(()=>data.value.bodies.slice(-7).map(x=>x.score));const events=computed(()=>data.value.tasks.map(x=>({id:x.id,title:x.title,date:x.taskDate,classNames:x.done?['fc-task-done']:[]})))
const calendarOptions=computed(()=>({plugins:[dayGridPlugin,interactionPlugin],initialView:'dayGridDay',initialDate:new Date(),headerToolbar:{left:'prev,next',center:'title',right:'dayGridDay,dayGridMonth'},height:'auto',events:events.value,dateClick:(info:{dateStr:string})=>{bodyNote.value=`${info.dateStr} 的待办`}}))
async function load(){try{const [today,tagData,planData]=await Promise.all([api.today(),api.moodTags(),api.plans()]);data.value=today;tags.value=tagData.items;plans.value=planData.items.filter(x=>x.timeProgress>=0&&x.timeProgress<=100&&x.progress<100)}catch(e){error.value=e instanceof Error?e.message:'读取失败'}}
async function recordMood(){try{await api.addMood(selectedTags.value,moodNote.value,false);selectedTags.value=[];moodNote.value='';await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function recordBody(){try{await api.addBody(bodyScore.value,bodyNote.value,false);bodyNote.value='';await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function toggleTask(id:string,done:boolean){try{await api.setTaskDone(id,done);await load()}catch(e){error.value=e instanceof Error?e.message:'更新失败'}}
function saveDiary(){if(timer)clearTimeout(timer);timer=window.setTimeout(async()=>{try{await api.saveDraft(data.value.diary.content);await api.saveDiary(data.value.diary.content);savedAt.value=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}catch(e){error.value=e instanceof Error?e.message:'保存失败'}},700)}
function startResize(event:PointerEvent){dragging.value=true;(event.currentTarget as HTMLElement).setPointerCapture(event.pointerId);const move=(e:PointerEvent)=>{leftWidth.value=Math.max(32,Math.min(68,e.clientX/window.innerWidth*100));localStorage.setItem('now-left-width',String(leftWidth.value))};const up=()=>{dragging.value=false;window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up)}
onMounted(()=>{clock=window.setInterval(()=>now.value=new Date(),1000);load()});onBeforeUnmount(()=>{if(clock)clearInterval(clock);if(timer)clearTimeout(timer)})
</script>
<template><main class="page now-page"><p v-if="error" class="error">{{error}}</p><section class="now-layout" :style="{'--left-width':`${leftWidth}%`}"><div class="now-left"><section class="now-clock"><strong>{{dateLabel}}</strong><span>{{lunar}}</span><time>{{timeLabel.slice(0,5)}}<small>{{timeLabel.slice(5)}}</small></time></section><div v-if="plans.length" class="plan-banner"><button v-for="plan in plans.slice(0,1)" :key="plan.id"><b>{{plan.name}}</b><span class="banner-bar"><i :style="{width:`${plan.timeProgress}%`}"/></span><span class="banner-bar plan"><i :style="{width:`${plan.progress}%`}"/></span></button></div><article class="now-card metric-card"><div class="metric-chart"><MetricLine :values="bodyValues"/><span>近七日</span></div><form @submit.prevent="recordBody"><h2>身体</h2><output>{{bodyScore}}</output><input v-model.number="bodyScore" type="range" min="0" max="100"/><input v-model="bodyNote" placeholder="备注"/><button class="primary">记录</button></form></article><article class="now-card metric-card"><div class="metric-chart"><MetricLine :values="moodValues"/><span>今日</span></div><form @submit.prevent="recordMood"><h2>心情</h2><div class="tag-grid"><button v-for="tag in tags" :key="tag.id" type="button" class="tag-item" :class="{selected:selectedTags.includes(tag.id)}" @click="selectedTags.includes(tag.id)?selectedTags=selectedTags.filter(x=>x!==tag.id):selectedTags.push(tag.id)"><i>{{tag.emoji}}</i><span>{{tag.name}}</span></button></div><input v-model="moodNote" placeholder="备注"/><button class="primary" :disabled="!selectedTags.length">记录</button></form></article><article class="now-card diary-card"><header><h2>日记</h2><small v-if="savedAt">已保存 {{savedAt}}</small></header><MdEditor v-model="data.diary.content" language="zh-CN" :preview="true" @onChange="saveDiary" @onSave="saveDiary"/></article></div><div class="now-divider" :class="{dragging}" @pointerdown="startResize"/><aside class="now-right"><section class="task-head"><h2>待办</h2><span>{{data.tasks.filter(x=>!x.done).length}}</span></section><FullCalendar :options="calendarOptions"/><ul class="today-tasks"><li v-for="task in data.tasks" :key="task.id"><input :checked="task.done" type="checkbox" @change="toggleTask(task.id,!task.done)"/><span :class="{done:task.done}">{{task.title}}</span></li></ul></aside></section></main></template>