<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, type MoodTag, type NowData } from '../api/client'
const data=ref<NowData>({diary:{id:'',entryDate:'',content:''},moods:[],bodies:[],tasks:[]});const attachments=ref<string[]>([]);const tags=ref<MoodTag[]>([]);const moodTagIDs=ref<string[]>([]);const moodNote=ref('');const bodyScore=ref(70);const bodyNote=ref('');const taskTitle=ref('');const taskDescription=ref('');const taskPriority=ref('normal');const newTag=ref({name:'',emoji:'🙂',value:50});const saving=ref(false);const error=ref('');let timer:number|undefined
const selectedTags=computed(()=>tags.value.filter(x=>moodTagIDs.value.includes(x.id)));const lastMood=computed(()=>data.value.moods.at(-1));const lastBody=computed(()=>data.value.bodies.at(-1));
async function load(){try{const [today,tagResult]=await Promise.all([api.today(),api.moodTags()]);data.value=today;tags.value=tagResult.items}catch(e){error.value=e instanceof Error?e.message:'读取今日数据失败'}}
async function recordMood(){try{await api.addMood(selectedTags.value.map(x=>x.id),moodNote.value);moodNote.value='';moodTagIDs.value=[];await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function recordBody(){try{await api.addBody(bodyScore.value,bodyNote.value);bodyNote.value='';await load()}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function addTag(){try{await api.addMoodTag(newTag.value);newTag.value={name:'',emoji:'🙂',value:50};await load()}catch(e){error.value=e instanceof Error?e.message:'创建标签失败'}}
function scheduleDiary(){if(timer)window.clearTimeout(timer);timer=window.setTimeout(saveDiary,700)}
async function saveDiary(){saving.value=true;try{await api.saveDraft(data.value.diary.content);await api.saveDiary(data.value.diary.content)}catch(e){error.value=e instanceof Error?e.message:'日记保存失败'}finally{saving.value=false}}
async function upload(event:Event){const file=(event.target as HTMLInputElement).files?.[0];if(!file)return;try{const attachment=await api.uploadAttachment(file);attachments.value.push(attachment.originalName)}catch(e){error.value=e instanceof Error?e.message:'上传失败'}finally{(event.target as HTMLInputElement).value=''}}
async function addTask(){try{await api.addTask(taskTitle.value,taskDescription.value,taskPriority.value);taskTitle.value='';taskDescription.value='';await load()}catch(e){error.value=e instanceof Error?e.message:'添加任务失败'}}
async function toggleTask(id:string,done:boolean){try{await api.setTaskDone(id,done);await load()}catch(e){error.value=e instanceof Error?e.message:'更新任务失败'}}
onMounted(load)
</script>
<template><main class="now-page"><header class="now-header"><div><p class="eyebrow">NOW / {{ data.diary.entryDate || 'LOADING' }}</p><h1>此刻</h1></div><time>{{ new Date().toLocaleString('zh-CN',{hour12:false}) }}</time></header><p v-if="error" class="error">{{error}}</p><div class="now-grid"><section class="stack"><article class="panel metric"><header><h2>身体</h2><small v-if="lastBody">最近 {{lastBody.score}} / 100</small></header><div class="bar"><i :style="{width:`${lastBody?.score ?? 0}%`}"/></div><form @submit.prevent="recordBody" class="compact"><input v-model.number="bodyScore" type="range" min="0" max="100"/><input v-model="bodyNote" placeholder="身体备注（可选）"/><button class="primary">记录 {{bodyScore}}</button></form></article><article class="panel metric"><header><h2>心情</h2><small v-if="lastMood">最近 {{lastMood.value.toFixed(1)}}</small></header><div class="tag-grid"><button v-for="tag in tags" :key="tag.id" type="button" class="tag" :class="{selected:moodTagIDs.includes(tag.id)}" @click="moodTagIDs.includes(tag.id)?moodTagIDs=moodTagIDs.filter(id=>id!==tag.id):moodTagIDs.push(tag.id)"><span>{{tag.emoji}}</span>{{tag.name}}</button></div><form @submit.prevent="recordMood" class="compact"><input v-model="moodNote" placeholder="心情备注（可选）"/><button class="primary" :disabled="selectedTags.length===0">记录心情</button></form><details><summary>新建心情标签</summary><form @submit.prevent="addTag" class="new-tag"><input v-model="newTag.emoji" aria-label="图标" maxlength="4"/><input v-model="newTag.name" placeholder="名称" required/><input v-model.number="newTag.value" type="number" min="1" placeholder="数值" required/><button>添加</button></form></details></article><article class="panel diary"><header><h2>今日日记</h2><small>{{saving?'保存中…':'自动保存'}}</small></header><textarea v-model="data.diary.content" placeholder="写下此刻…（支持 Markdown）" @input="scheduleDiary"/><label class="attachment-picker">添加附件（最大 20MB）<input type="file" @change="upload"/></label><small v-if="attachments.length">本次已上传：{{attachments.join('、')}}</small></article></section><section class="panel tasks"><header><h2>今日待办</h2><span>{{data.tasks.filter(x=>!x.done).length}} 项未完成</span></header><form @submit.prevent="addTask" class="task-form"><input v-model.trim="taskTitle" placeholder="添加任务" required/><select v-model="taskPriority"><option value="low">低</option><option value="normal">普通</option><option value="high">高</option></select><input v-model="taskDescription" placeholder="说明（可选）"/><button class="primary">添加</button></form><ul><li v-for="task in data.tasks" :key="task.id" :class="{done:task.done}"><input :checked="task.done" type="checkbox" @change="toggleTask(task.id,!task.done)"/><div><b>{{task.title}}</b><small v-if="task.description">{{task.description}}</small></div><em :class="task.priority">{{task.priority==='high'?'高':task.priority==='low'?'低':'普通'}}</em></li><li v-if="data.tasks.length===0" class="empty">今天还没有待办。</li></ul></section></div></main></template>