<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { api, type HistoryDay, type HistoryRange } from '../api/client'
const today=new Date();const iso=(value:Date)=>value.toISOString().slice(0,10);const offset=(days:number)=>{const value=new Date(today);value.setDate(value.getDate()+days);return iso(value)}
const range=ref<HistoryRange>({from:offset(-13),to:iso(today),days:[],points:[]});const selected=ref('');const loading=ref(false);const error=ref('');const zoom=ref(14)
const selectedDay=computed<HistoryDay|undefined>(()=>range.value.days.find(x=>x.date===selected.value));const moodPoints=computed(()=>range.value.points.filter(x=>x.mood!==null));const bodyPoints=computed(()=>range.value.points.filter(x=>x.body!==null))
async function load(){loading.value=true;error.value='';try{range.value=await api.history(range.value.from,range.value.to);selected.value=range.value.to}catch(e){error.value=e instanceof Error?e.message:'历史读取失败'}finally{loading.value=false}}
function shift(days:number){const from=new Date(`${range.value.from}T00:00:00`);const to=new Date(`${range.value.to}T00:00:00`);from.setDate(from.getDate()+days);to.setDate(to.getDate()+days);if(to>today){const delta=Math.round((to.getTime()-today.getTime())/86400000);from.setDate(from.getDate()-delta);to.setDate(today.getDate())};range.value={...range.value,from:iso(from),to:iso(to)};load()}
function applyZoom(){const end=new Date(`${range.value.to}T00:00:00`);const start=new Date(end);start.setDate(end.getDate()-zoom.value+1);range.value={...range.value,from:iso(start)};load()}
onMounted(load)
</script>
<template><main class="past-page"><header class="past-header"><div><p class="eyebrow">PAST / CHRONICLE</p><h1>过去</h1></div><div class="past-controls"><button @click="shift(-zoom)">← 更早</button><label>范围 <input v-model.number="zoom" type="range" min="3" max="90" @change="applyZoom"/> {{zoom}} 天</label><button @click="shift(zoom)">更近 →</button></div></header><p v-if="error" class="error">{{error}}</p><p v-if="loading" class="empty">正在读取并过滤历史内容…</p><template v-else><section class="past-layout"><aside class="timeline"><button v-for="day in range.days" :key="day.date" :class="{selected:day.date===selected}" @click="selected=day.date"><time>{{day.date.slice(5)}}</time><i v-if="day.milestoneCount">✦</i><span v-if="day.diary.id || day.tasks.length || day.moodCount || day.bodyCount"/></button></aside><section class="past-main"><div class="trend-grid"><article class="past-card"><h2>心情趋势</h2><div class="spark"><i v-for="point in moodPoints" :key="point.date" :style="{height:`${Math.max(6,Math.min(100,point.mood ?? 0))}%`}"/></div></article><article class="past-card"><h2>身体趋势</h2><div class="spark"><i v-for="point in bodyPoints" :key="point.date" :style="{height:`${Math.max(6,Math.min(100,point.body ?? 0))}%`}"/></div></article></div><div v-if="selectedDay" class="day-split"><article class="past-card"><header><h2>{{selectedDay.date}} · 日记</h2><span v-if="selectedDay.milestoneCount">✦ {{selectedDay.milestoneCount}} 个里程碑</span></header><pre v-if="selectedDay.diary.id">{{selectedDay.diary.content}}</pre><p v-else class="empty">当天没有你可访问的日记。</p><footer>心情 {{selectedDay.moodCount}} 条 · 身体 {{selectedDay.bodyCount}} 条</footer></article><article class="past-card"><h2>当日日程</h2><ul class="reader-list"><li v-for="task in selectedDay.tasks" :key="task.id" :class="{done:task.done}"><b>{{task.title}}</b><span>{{task.description}}</span></li><li v-if="!selectedDay.tasks.length" class="empty">当天没有你可访问的任务。</li></ul></article></div></section></section></template></main></template>