<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import MetricLine from '../components/MetricLine.vue'
import { api, type HistoryDay, type HistoryRange } from '../api/client'
const today=new Date();const iso=(value:Date)=>value.toISOString().slice(0,10);const add=(v:Date,d:number)=>{const x=new Date(v);x.setDate(x.getDate()+d);return x};const zoom=ref(14);const anchor=ref(today);const range=ref<HistoryRange>({from:iso(add(today,-13)),to:iso(today),days:[],points:[]});const selected=ref(iso(today));const error=ref('');let dragStart:{y:number;date:Date}|null=null
const selectedDay=computed<HistoryDay|undefined>(()=>range.value.days.find(x=>x.date===selected.value));const mood=computed(()=>range.value.points.map(x=>x.mood??0));const body=computed(()=>range.value.points.map(x=>x.body??0))
async function load(){const end=anchor.value>today?today:anchor.value;const start=add(end,-zoom.value+1);try{range.value=await api.history(iso(start),iso(end));if(!range.value.days.some(x=>x.date===selected.value))selected.value=range.value.to}catch(e){error.value=e instanceof Error?e.message:'读取失败'}}
function wheel(e:WheelEvent){e.preventDefault();zoom.value=Math.max(3,Math.min(365,e.deltaY<0?Math.round(zoom.value*.7):Math.round(zoom.value*1.4)));load()}function down(e:PointerEvent){dragStart={y:e.clientY,date:new Date(anchor.value)};(e.currentTarget as HTMLElement).setPointerCapture(e.pointerId)}function move(e:PointerEvent){if(!dragStart)return;anchor.value=add(dragStart.date,Math.round((dragStart.y-e.clientY)/14));if(anchor.value>today)anchor.value=today;load()}function up(){dragStart=null}onMounted(load)
</script>
<template><main class="page past-page"><p v-if="error" class="error">{{error}}</p><section class="past-layout"><aside class="life-axis" @wheel="wheel" @pointerdown="down" @pointermove="move" @pointerup="up"><button v-for="day in range.days" :key="day.date" :class="{selected:day.date===selected}" @click="selected=day.date"><span v-if="day.milestoneCount" class="medal">✦</span><time>{{day.date.slice(5)}}</time><i v-if="day.date===range.to"/></button></aside><section class="past-content"><div class="past-trends"><article class="past-card"><h2>心情</h2><MetricLine :values="mood"/></article><article class="past-card"><h2>身体</h2><MetricLine :values="body"/></article></div><div v-if="selectedDay" class="past-day"><article class="past-card diary-render"><header><h2>{{selectedDay.date}}</h2><span v-if="selectedDay.milestoneCount" class="medal">✦</span></header><div v-if="selectedDay.diary.id" class="markdown-view">{{selectedDay.diary.content}}</div><div v-else class="empty">这一天没有可查看的日记</div></article><article class="past-card"><h2>日程</h2><ul class="past-tasks"><li v-for="task in selectedDay.tasks" :key="task.id" :class="{done:task.done}"><span>{{task.title}}</span><small>{{task.description}}</small></li><li v-if="!selectedDay.tasks.length" class="empty">这一天没有可查看的日程</li></ul></article></div></section></section></main></template>